/**
 * @fileoverview The application store is used to store the application data
 * for the current user. The data is stored in the browser's session storage and
 * is used to populate the application form as well as to persist the data
 * when the user navigates through the application process.
 *
 * This store does not manage the current step of the application process.
 * For that, see the StepContext.
 *
 * In this file the subApplications' id is equal to the eventId. This is because
 * each subEvent can only have one subApplication and we haven't created an
 * identifier for the subApplication yet (automatically generated by the database).
 */
'use client';

import { Prisma } from '@prisma/client';
import React from 'react';
import { z } from 'zod';
import { createStore, StateCreator, useStore } from 'zustand';
import { persist } from 'zustand/middleware';
import { immer } from 'zustand/middleware/immer';
import { generalFormSchema } from './general-form';

export interface SubApplicationSelection
  extends Omit<
    Prisma.SubApplicationCreateInput,
    'application' | 'subEvent' | 'id'
  > {
  eventName: string;
  subEventId: string;
  slotId: string;
}

// #region Slice Types
// ============================================================

interface GeneralState {
  /**
   * The general form data for the current user. This is the data
   * which the user has entered into the general form.
   */
  general: z.infer<typeof generalFormSchema>;
}

interface GeneralActions {
  /**
   * Sets the general form data for the current user.
   *
   * @param general - The general form data to set.
   */
  setGeneral: (general: z.infer<typeof generalFormSchema>) => void;
}

type GeneralSlice = GeneralState & GeneralActions;

interface SubApplicationState {
  /**
   * The subApplications object is a record of all the sub applications
   * that the user has created by selecting sub events.
   *
   * Sub Applications are automatically grouped by their slotId when
   * they are created. The slotId is the id of the slot that the sub
   * application belongs to.
   */
  subApplications: Record<string, SubApplicationSelection[]>;
}

interface SubApplicationActions {
  /**
   * Searches for a sub application by checking the slotId and eventId. If
   * no sub application is found, the function returns undefined.
   *
   * @param slotId - The slotId of the slot in which the sub application is
   * located.
   * @param eventId - The eventId of the sub application to search for.
   *
   * @returns The sub application if found, otherwise undefined.
   */
  getSubApplication: (
    slotId: string,
    eventId: string
  ) => SubApplicationSelection | undefined;

  /**
   * Adds a new sub application to the store. If the slotId already exists,
   * the sub application will be added to the array. If the slotId does not
   * exist, a new array will be created and the sub application will be added
   * to it.
   *
   * If a sub application with the same slotId and eventId already exists,
   * the function aborts.
   *
   * @param subApplication - The sub application to add.
   */
  addSubApplication: (subApplication: SubApplicationSelection) => void;

  /**
   * Removes a sub application from the store by checking the slotId and
   * subEventId. If both match, the sub application is removed.
   *
   * @param slotId - The slotId of the slot in which the sub application is
   * located.
   * @param subEventId - The subEventId of the sub application to remove.
   */
  removeSubApplication: (slotId: string, subEventId: string) => void;

  /**
   * Sets the field `prioritized` of the sub application to true.
   *
   * @param slotId - The slotId of the slot in which the sub application is
   * located.
   * @param subEventId - The subEventId of the sub application to prioritize.
   */
  prioritizeSubApplication: (slotId: string, subEventId: string) => void;

  /**
   * Removes the field `prioritized` of the sub application.
   *
   * @param slotId - The slotId of the slot in which the sub application is
   * located.
   * @param subEventId - The subEventId of the sub application to unprioritize.
   */
  unprioritizeSubApplication: (slotId: string, subEventId: string) => void;

  /**
   * Updates a sub application by checking the slotId and subEventId. If both
   * match, the sub application is updated.
   *
   * @param slotId - The slotId of the slot in which the sub application is
   */
  updateSubApplication: (
    slotId: string,
    subApplication: Pick<SubApplicationSelection, 'subEventId'> &
      Partial<Omit<SubApplicationSelection, 'subEventId'>>
  ) => void;
}

type SubApplicationSlice = SubApplicationState & SubApplicationActions;

type Slices = GeneralSlice & SubApplicationSlice;

// #region default state
// ============================================================

export const defaultState: SubApplicationState & GeneralState = {
  general: {
    firstName: '',
    lastName: '',
    birthDate: new Date(),
    gender: 'MALE',
    currentDegree: 'ABITUR',
    university: '',
    abiturGrade: 0,
    targetDegree: 'BACHELOR',
    expectedGraduationYear: 0,
    fieldOfStudy: '',
    semester: 0,
    currentGpa: 0,
    experienceConsulting: 0,
    experienceAbroad: 0,
  },
  subApplications: {},
};

// #region General Slice
// ============================================================
export const createGeneralSlice: StateCreator<
  Slices,
  [['zustand/immer', never], ['zustand/persist', unknown]],
  [],
  GeneralSlice
> = (set) => ({
  // state
  general: defaultState.general,

  // actions
  setGeneral(general) {
    set({ general });
  },
});

// #region Sub Application Slice
// ============================================================
export const createSubApplicationSlice: StateCreator<
  Slices,
  [['zustand/immer', never], ['zustand/persist', unknown]],
  [],
  SubApplicationSlice
> = (set, get) => ({
  // state
  subApplications: defaultState.subApplications,

  // actions
  getSubApplication(slotId, eventId) {
    return get().subApplications[slotId]?.find(
      (subApplication) => subApplication.subEventId === eventId
    );
  },

  addSubApplication(subApplication) {
    set((state) => {
      const slotId = subApplication.slotId;

      if (!state.subApplications[slotId]) {
        state.subApplications[slotId] = [];
      }

      state.subApplications[slotId].push(subApplication);
    });
  },

  removeSubApplication(slotId, subEventId) {
    set((state) => {
      state.subApplications[slotId] = state.subApplications[slotId].filter(
        (subApplication) => subApplication.subEventId !== subEventId
      );
    });
  },

  updateSubApplication(slotId, subApplication) {
    set((state) => {
      // Find the sub application to update
      const subApplicationIndex = state.subApplications[slotId].findIndex(
        (app) => app.subEventId === subApplication.subEventId
      );

      // If the sub application exists, update it
      if (subApplicationIndex !== -1) {
        // Merge the existing sub application with the updates
        state.subApplications[slotId][subApplicationIndex] = {
          ...state.subApplications[slotId][subApplicationIndex],
          ...subApplication,
        };
      }
    });
  },

  prioritizeSubApplication(slotId, subEventId) {
    set((state) => {
      const subApplication = state.subApplications[slotId].find(
        (app) => app.subEventId == subEventId
      );
      if (subApplication) {
        subApplication.prioritized = true;
      }
    });
  },

  unprioritizeSubApplication(slotId, subEventId) {
    set((state) => {
      const subApplication = state.subApplications[slotId].find(
        (app) => app.subEventId == subEventId
      );
      if (subApplication) {
        subApplication.prioritized = false;
      }
    });
  },
});

// #region Store
// ============================================================
export const createApplicationStore = () => {
  return createStore<Slices>()(
    immer(
      persist(
        (...args) => ({
          ...createGeneralSlice(...args),
          ...createSubApplicationSlice(...args),
        }),
        {
          name: 'test',
        }
      )
    )
  );
};

// #region Context
// ============================================================
export type ApplicationStoreApi = ReturnType<typeof createApplicationStore>;

export const ApplicationStoreContext = React.createContext<
  ApplicationStoreApi | undefined
>(undefined);

export interface ApplicationStoreProviderProps {
  children: React.ReactNode;
}

export function ApplicationStoreProvider({
  children,
}: ApplicationStoreProviderProps) {
  const storeRef = React.useRef<ApplicationStoreApi | null>(null);

  if (storeRef.current === null) {
    storeRef.current = createApplicationStore();
  }

  return (
    <ApplicationStoreContext.Provider value={storeRef.current}>
      {children}
    </ApplicationStoreContext.Provider>
  );
}

export function useApplicationStore<T>(selector: (store: Slices) => T): T {
  const applicationStoreContext = React.useContext(ApplicationStoreContext);

  if (!applicationStoreContext) {
    throw new Error(
      'useApplicationStore must be used within a ApplicationStoreProvider'
    );
  }

  return useStore(applicationStoreContext, selector);
}
