name: Validate Pull Request

on:
  pull_request:
    branches:
      - development
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_ENV: development
      NEXT_PUBLIC_SUPABASE_URL: http://127.0.0.1:54321
      NEXT_PUBLIC_SUPABASE_ANON_KEY: THIS_IS_A_TEST_KEY_AND_SHOULD_NOT_BE_USED_IN_PRODUCTION

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check code formatting
        run: pnpm format:check

      - name: Run linter
        run: pnpm lint

      - name: Run tests
        run: pnpm test
